### ISSUE TITLE
Alterar modelo POST de unidade e organização para permitir informar GUID no lugar de ID.

### ISSUE THREAD

**Issue by fernandoslv** [prodest/organograma-web-api#51]
Alterar modelo POST de unidade e organização para permitir informar GUID de organização e unidade pai no lugar de ID de organização e de unidade pai.

**Comment by brenowschneider** [comment]
POST organização: organização pai e município do endereço estão preparados para receber guid ao invés de id.

**Comment by fontourafernando** [comment]
Issue concluída.
