### ISSUE TITLE
Deploy no ambiente de demonstração

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/organograma-web-api#56]
1) Criar branch demo o Git
2) Solicitar criação de um novo ambente demo no Docker
3) Alterar os arquivos de configuração de Deploy
4) Configurar variáveis de ambiente no Docker
5) Solicitar apontamento de ARR para o endereço https://sistemas.es.gov.br/prodest/processoeletronicodemo

**Comment by brenowschneider** [comment]
Branch "demo" criada e alinhada com a branch "develop"
